### PR TITLE
Allow option to include full file path in CSV/JSON

### PR DESCRIPTION
**Pull request by CSobol**
We have a use case in which we need to report the absolute file path to act on it later on in our script, so I wrote the functionality.

### CODE REVIEW

**Comment by CSobol** [comment]
yeesh forked off the wrong repo

**Comment by CSobol** [comment]
Yeesh, realized that the library i'm using (npm-license-checker) uses this branch, so... reopening.

**Comment by mwittig** [comment]
Excellent. Are you planning to file a PR npm-license-checker, too?

**Comment by CSobol** [comment]
I might be making one for that. Not sure at the moment as I'm not using it as a CLI tool, I'm wrapping it in some node with the inquirer package to make an interactive tool.

The work to make it take this command switch is pretty minimal, though, so there's a good chance I can get to it at some point this week.

**Pull request merged**
